### PR TITLE
Including M1 simulator support

### PR DESCRIPTION
**Pull request by m0rb1u5**
Including M1 simulator support

### CODE REVIEW

**Comment by vitalyster** [comment]
If you want to merge changes back, README urls should not be changed to your fork, right?

**Review by vitalyster — CHANGES_REQUESTED** [review]
README updates are wrong

**Comment by m0rb1u5** [comment]
That's right. The urls were changed.

**Review by vitalyster — APPROVED** [review]

**Review by vitalyster — CHANGES_REQUESTED** [review]
I tried to use your package with simulator, but it does not have actual arm64 slice in ios-arm64_x86_64-simulator framework (you can examine it with `file` command)

**Comment by m0rb1u5** [comment]
Here it is
Captura de Tela 2021-04-22 às 16 12 04

**Comment by m0rb1u5** [comment]
Weird, here I have two slices:

WebRTC: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
WebRTC (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
WebRTC (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64

**Comment by vitalyster** [comment]
Sorry, it was my bad, I need to specify 1.1.4 version when adding a package. I can confirm it works on M1 simulator

**Review by vitalyster — APPROVED** [review]

**Comment by tyten** [comment]
Out of curiosity, what steps did you do in order to add Apple Silicon simulator support?

**Comment by alexpiezo** [comment]
the repo has been updated to build with GH actions #3

**Pull request closed without merging**
